//! Embedded SudachiDict dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedSudachiDictLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-sudachidict", EmbeddedSudachiDictLoader);
