//! Embedded ipadic-neologd dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedIPADICNEologdLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-ipadic-neologd", EmbeddedIPADICNEologdLoader);
