//! Embedded ko-dic dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedKoDicLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-ko-dic", EmbeddedKoDicLoader);
