[book]
authors = ["Lindera Project"]
language = "ja"
multilingual = false
src = "src"
title = "Lindera ドキュメント"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/lindera/lindera"
site-url = "/lindera/ja/"
additional-js = ["../mermaid.min.js", "../mermaid-init.js"]
