/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A morphological analysis dictionary.
 *
 * Contains the data structures needed for tokenization and morphological analysis.
 */
export declare class Dictionary {
  /** Returns the name of the dictionary metadata. */
  metadataName(): string
  /** Returns the character encoding of the dictionary. */
  metadataEncoding(): string
  /** Returns the full metadata object of the dictionary. */
  metadata(): JsMetadata
}
export type JsDictionary = Dictionary

/**
 * Dictionary metadata configuration.
 *
 * A thin napi wrapper over [`lindera_binding_core::CoreMetadata`], which owns
 * the default values and the schema wiring.
 */
export declare class Metadata {
  /**
   * Creates a new Metadata with optional configuration.
   *
   * # Arguments
   *
   * * `options` - Optional configuration object. When omitted, all defaults are used.
   */
  constructor(options?: MetadataOptions | undefined | null)
  /**
   * Creates a Metadata with all default values.
   *
   * # Returns
   *
   * A Metadata instance with default configuration.
   */
  static createDefault(): Metadata
  /**
   * Loads metadata from a JSON file.
   *
   * # Arguments
   *
   * * `path` - Path to the JSON metadata file.
   *
   * # Returns
   *
   * A Metadata instance loaded from the file.
   */
  static fromJsonFile(path: string): Metadata
  /** Dictionary name. */
  get name(): string
  /** Sets the dictionary name. */
  set name(name: string)
  /** Character encoding. */
  get encoding(): string
  /** Sets the character encoding. */
  set encoding(encoding: string)
  /** Default word cost. */
  get defaultWordCost(): number
  /** Sets the default word cost. */
  set defaultWordCost(cost: number)
  /** Default left context ID. */
  get defaultLeftContextId(): number
  /** Sets the default left context ID. */
  set defaultLeftContextId(id: number)
  /** Default right context ID. */
  get defaultRightContextId(): number
  /** Sets the default right context ID. */
  set defaultRightContextId(id: number)
  /** Default field value for missing fields. */
  get defaultFieldValue(): string
  /** Sets the default field value. */
  set defaultFieldValue(value: string)
  /** Whether flexible CSV parsing is enabled. */
  get flexibleCsv(): boolean
  /** Sets flexible CSV parsing. */
  set flexibleCsv(value: boolean)
  /** Whether to skip entries with invalid cost or ID. */
  get skipInvalidCostOrId(): boolean
  /** Sets whether to skip invalid entries. */
  set skipInvalidCostOrId(value: boolean)
  /** Whether to normalize morphological details. */
  get normalizeDetails(): boolean
  /** Sets whether to normalize details. */
  set normalizeDetails(value: boolean)
  /**
   * Returns a plain object representation of the metadata.
   *
   * # Returns
   *
   * A HashMap containing all metadata properties as strings.
   */
  toObject(): Record<string, string>
}
export type JsMetadata = Metadata

/**
 * N-best tokenization result.
 *
 * Contains a list of tokens and their total path cost.
 */
export declare class NbestResult {
  /** Tokens in this result. */
  get tokens(): Array<Token>
  /** Total path cost of this tokenization. */
  get cost(): number
}
export type JsNbestResult = NbestResult

/**
 * Dictionary schema definition.
 *
 * A thin napi wrapper over [`lindera_binding_core::CoreSchema`], which owns the
 * field storage, the name-to-index map, and the field lookups.
 */
export declare class Schema {
  /**
   * Creates a new schema with the specified field names.
   *
   * # Arguments
   *
   * * `fields` - Array of field name strings.
   */
  constructor(fields: Array<string>)
  /**
   * Creates a default schema matching the IPADIC format (13 fields).
   *
   * # Returns
   *
   * A schema with the standard IPADIC field definitions.
   */
  static createDefault(): Schema
  /** Returns the field names in the schema. */
  get fields(): Array<string>
  /**
   * Returns the index of the specified field name.
   *
   * # Arguments
   *
   * * `field_name` - Name of the field to look up.
   *
   * # Returns
   *
   * The zero-based index of the field, or `undefined` if not found.
   */
  getFieldIndex(fieldName: string): number | null
  /** Returns the total number of fields in the schema. */
  fieldCount(): number
  /**
   * Returns the field name at the specified index.
   *
   * # Arguments
   *
   * * `index` - Zero-based index.
   *
   * # Returns
   *
   * The field name, or `undefined` if the index is out of range.
   */
  getFieldName(index: number): string | null
  /**
   * Returns the custom fields (index 4 and above).
   *
   * # Returns
   *
   * An array of custom field names.
   */
  getCustomFields(): Array<string>
  /**
   * Returns all field names in the schema.
   *
   * # Returns
   *
   * An array of all field names.
   */
  getAllFields(): Array<string>
  /**
   * Returns the field definition for the specified field name.
   *
   * # Arguments
   *
   * * `name` - Name of the field to look up.
   *
   * # Returns
   *
   * The field definition, or `undefined` if not found.
   */
  getFieldByName(name: string): JsFieldDefinition | null
  /**
   * Validates that a CSV record matches the schema.
   *
   * # Arguments
   *
   * * `record` - Array of field values to validate.
   */
  validateRecord(record: Array<string>): void
}
export type JsSchema = Schema

/**
 * A morphological token.
 *
 * Represents a single token from morphological analysis with its surface form,
 * position information, and morphological details.
 */
export declare class Token {
  /** Surface form of the token. */
  get surface(): string
  /** Start byte position in the original text. */
  get byteStart(): number
  /** End byte position in the original text. */
  get byteEnd(): number
  /** Position index of the token. */
  get position(): number
  /** Word ID in the dictionary. */
  get wordId(): number
  /** Whether this token is an unknown word (not found in the dictionary). */
  get isUnknown(): boolean
  /** Morphological details of the token (part of speech, reading, etc.). */
  get details(): Array<string>
  /**
   * Returns the detail string at the specified index.
   *
   * # Arguments
   *
   * * `index` - Zero-based index into the details array.
   *
   * # Returns
   *
   * The detail string if found, or `null` if the index is out of range.
   */
  getDetail(index: number): string | null
}
export type JsToken = Token

/**
 * Tokenizer for performing morphological analysis.
 *
 * The tokenizer processes text and returns tokens with their morphological features.
 */
export declare class Tokenizer {
  /**
   * Creates a new tokenizer with the given dictionary and mode.
   *
   * # Arguments
   *
   * * `dictionary` - Dictionary to use for tokenization.
   * * `mode` - Tokenization mode ("normal" or "decompose"). Default: "normal".
   * * `user_dictionary` - Optional user dictionary for custom words.
   */
  constructor(dictionary: Dictionary, mode?: string | undefined | null, userDictionary?: UserDictionary | undefined | null)
  /**
   * Tokenizes the given text.
   *
   * # Arguments
   *
   * * `text` - Text to tokenize.
   *
   * # Returns
   *
   * An array of Token objects containing morphological features.
   */
  tokenize(text: string): Array<Token>
  /**
   * Tokenizes the given text and returns tokens as plain JS objects.
   *
   * This is the predictable-memory path for high-volume use: plain
   * objects are reclaimed by ordinary GC, while `Token` class instances
   * release native memory via an event-loop-deferred finalizer, so
   * synchronous loops that never yield accumulate memory with `tokenize`.
   *
   * In 6.x, `tokenize` itself will return plain objects and this method
   * will be removed. See <https://github.com/lindera/lindera/issues/930>.
   *
   * # Arguments
   *
   * * `text` - Text to tokenize.
   *
   * # Returns
   *
   * An array of plain token objects, in reading order.
   */
  tokenizeObjects(text: string): Array<JsTokenData>
  /**
   * Tokenizes the given text and returns only the token surfaces.
   *
   * This is the fast path for wakati-style use: no Token objects are
   * created and no morphological details are loaded, so it is
   * significantly faster than `tokenize` when only the surface strings
   * are needed. The surfaces equal `tokenize(text).map((t) => t.surface)`.
   *
   * # Arguments
   *
   * * `text` - Text to tokenize.
   *
   * # Returns
   *
   * An array of surface strings, in reading order.
   */
  tokenizeSurfaces(text: string): Array<string>
  /**
   * Tokenizes the given text and returns N-best results.
   *
   * # Arguments
   *
   * * `text` - Text to tokenize.
   * * `n` - Number of N-best results to return.
   * * `unique` - If true, deduplicate results (default: false).
   * * `cost_threshold` - Maximum cost difference from the best path (default: undefined).
   *
   * # Returns
   *
   * An array of NbestResult objects, each containing tokens and their cost.
   */
  tokenizeNbest(text: string, n: number, unique?: boolean | undefined | null, costThreshold?: number | undefined | null): Array<NbestResult>
}
export type JsTokenizer = Tokenizer

/**
 * Builder for creating a Tokenizer with custom configuration.
 *
 * The builder pattern allows for fluent configuration of tokenizer parameters including
 * dictionaries, modes, and filter pipelines.
 */
export declare class TokenizerBuilder {
  /** Creates a new TokenizerBuilder with default configuration. */
  constructor()
  /**
   * Loads configuration from a JSON file.
   *
   * # Arguments
   *
   * * `file_path` - Path to the configuration file.
   *
   * # Returns
   *
   * A new TokenizerBuilder with the loaded configuration.
   */
  fromFile(filePath: string): TokenizerBuilder
  /**
   * Sets the tokenization mode.
   *
   * # Arguments
   *
   * * `mode` - Mode string ("normal" or "decompose").
   */
  setMode(mode: string): void
  /**
   * Sets the dictionary path or URI.
   *
   * # Arguments
   *
   * * `path` - Path to the dictionary directory or embedded URI (e.g. "embedded://ipadic").
   */
  setDictionary(path: string): void
  /**
   * Sets the user dictionary URI.
   *
   * # Arguments
   *
   * * `uri` - URI to the user dictionary.
   */
  setUserDictionary(uri: string): void
  /**
   * Sets whether to keep whitespace in tokenization results.
   *
   * # Arguments
   *
   * * `keep_whitespace` - If true, whitespace tokens will be included in results.
   */
  setKeepWhitespace(keepWhitespace: boolean): void
  /**
   * Appends a character filter to the preprocessing pipeline.
   *
   * # Arguments
   *
   * * `kind` - Type of character filter to add (e.g. "unicode_normalize", "mapping").
   * * `args` - Optional filter arguments as a JSON-compatible object.
   */
  appendCharacterFilter(kind: string, args?: any | undefined | null): void
  /**
   * Appends a token filter to the postprocessing pipeline.
   *
   * # Arguments
   *
   * * `kind` - Type of token filter to add (e.g. "lowercase", "japanese_stop_tags").
   * * `args` - Optional filter arguments as a JSON-compatible object.
   */
  appendTokenFilter(kind: string, args?: any | undefined | null): void
  /**
   * Builds the tokenizer with the configured settings.
   *
   * # Returns
   *
   * A configured Tokenizer instance ready for use.
   */
  build(): JsTokenizer
}
export type JsTokenizerBuilder = TokenizerBuilder

/**
 * A user-defined dictionary for custom words.
 *
 * User dictionaries allow you to add custom words and their morphological features
 * that are not present in the main dictionary.
 */
export declare class UserDictionary {

}
export type JsUserDictionary = UserDictionary

/**
 * Builds a dictionary from source files.
 *
 * # Arguments
 *
 * * `input_dir` - Directory containing dictionary source files.
 * * `output_dir` - Directory where the built dictionary will be saved.
 * * `metadata` - Metadata configuration for the dictionary.
 */
export declare function buildDictionary(inputDir: string, outputDir: string, metadata: JsMetadata): void

/**
 * Builds a user dictionary from a CSV file.
 *
 * # Arguments
 *
 * * `kind` - Dictionary kind (reserved for future use).
 * * `input_file` - Path to the CSV file containing user dictionary entries.
 * * `output_dir` - Directory where the built user dictionary will be saved.
 * * `metadata` - Optional metadata configuration. If omitted, default values are used.
 */
export declare function buildUserDictionary(kind: string, inputFile: string, outputDir: string, metadata?: JsMetadata | undefined | null): void

/**
 * Exports dictionary files from a trained model.
 *
 * # Arguments
 *
 * * `options` - Export options containing file paths.
 */
export declare function exportModel(options: ExportOptions): void

/** Options for exporting a trained model. */
export interface ExportOptions {
  /** Path to the trained model file (.dat). */
  model: string
  /** Output directory for dictionary source files. */
  output: string
  /** Optional path to a base metadata.json file. */
  metadata?: string
}

/**
 * Field definition in dictionary schema.
 *
 * Describes a single field in the dictionary entry format.
 */
export interface JsFieldDefinition {
  /** Field index in the record. */
  index: number
  /** Field name. */
  name: string
  /** Field type. */
  fieldType: JsFieldType
  /** Optional description of the field. */
  description?: string
}

/**
 * Field type in dictionary schema.
 *
 * Defines the type of a field in the dictionary entry.
 */
export declare const enum JsFieldType {
  /** Surface form (word text) */
  Surface = 'Surface',
  /** Left context ID for morphological analysis */
  LeftContextId = 'LeftContextId',
  /** Right context ID for morphological analysis */
  RightContextId = 'RightContextId',
  /** Word cost (used in path selection) */
  Cost = 'Cost',
  /** Custom field (morphological features) */
  Custom = 'Custom'
}

/**
 * Tokenization mode.
 *
 * Determines how text is segmented into tokens.
 *
 * - `Normal`: Standard tokenization based on dictionary cost.
 * - `Decompose`: Decomposes compound words using penalty-based segmentation.
 */
export declare const enum JsMode {
  /** Standard tokenization based on dictionary cost */
  Normal = 'Normal',
  /** Decompose compound words using penalty-based segmentation */
  Decompose = 'Decompose'
}

/**
 * Penalty configuration for decompose mode.
 *
 * Controls how aggressively compound words are decomposed based on
 * character type and length thresholds.
 */
export interface JsPenalty {
  /** Length threshold for kanji sequences before applying penalty (default: 2). */
  kanjiPenaltyLengthThreshold: number
  /** Penalty value for long kanji sequences (default: 3000). */
  kanjiPenaltyLengthPenalty: number
  /** Length threshold for other character sequences before applying penalty (default: 7). */
  otherPenaltyLengthThreshold: number
  /** Penalty value for long other-character sequences (default: 1700). */
  otherPenaltyLengthPenalty: number
}

/**
 * Plain-object token data.
 *
 * Carries the same fields as [`JsToken`] but converts to a plain JS
 * object owned by the JS heap, with no native box or deferred finalizer.
 */
export interface JsTokenData {
  /** Surface form of the token. */
  surface: string
  /** Start byte position in the original text. */
  byteStart: number
  /** End byte position in the original text. */
  byteEnd: number
  /** Position index of the token. */
  position: number
  /** Word ID in the dictionary. */
  wordId: number
  /** Whether this token is an unknown word. */
  isUnknown: boolean
  /** Morphological details of the token. */
  details: Array<string>
}

/**
 * Loads a dictionary from the specified URI.
 *
 * # Arguments
 *
 * * `uri` - URI to the dictionary. Can be a file path or embedded dictionary URI
 *   (e.g. "embedded://ipadic").
 *
 * # Returns
 *
 * A loaded Dictionary object.
 */
export declare function loadDictionary(uri: string): Dictionary

/**
 * Loads a user dictionary from the specified URI.
 *
 * # Arguments
 *
 * * `uri` - URI to the user dictionary directory.
 * * `metadata` - Metadata configuration for the user dictionary.
 *
 * # Returns
 *
 * A loaded UserDictionary object.
 */
export declare function loadUserDictionary(uri: string, metadata: JsMetadata): UserDictionary

/**
 * Options for creating a Metadata instance.
 *
 * All fields are optional. When omitted, default values are used.
 */
export interface MetadataOptions {
  /** Dictionary name (default: "default"). */
  name?: string
  /** Character encoding (default: "UTF-8"). */
  encoding?: string
  /** Default cost for unknown words (default: -10000). */
  defaultWordCost?: number
  /** Default left context ID (default: 1288). */
  defaultLeftContextId?: number
  /** Default right context ID (default: 1288). */
  defaultRightContextId?: number
  /** Default value for missing fields (default: "*"). */
  defaultFieldValue?: string
  /** Allow flexible CSV parsing (default: false). */
  flexibleCsv?: boolean
  /** Skip entries with invalid cost or ID (default: false). */
  skipInvalidCostOrId?: boolean
  /** Normalize morphological details (default: false). */
  normalizeDetails?: boolean
}

/**
 * Trains a morphological analysis model from an annotated corpus.
 *
 * # Arguments
 *
 * * `options` - Training options containing file paths and parameters.
 */
export declare function train(options: TrainOptions): void

/** Options for training a CRF model. */
export interface TrainOptions {
  /** Path to the seed lexicon file (CSV format). */
  seed: string
  /** Path to the annotated training corpus. */
  corpus: string
  /** Path to the character definition file (char.def). */
  charDef: string
  /** Path to the unknown word definition file (unk.def). */
  unkDef: string
  /** Path to the feature definition file (feature.def). */
  featureDef: string
  /** Path to the rewrite rule definition file (rewrite.def). */
  rewriteDef: string
  /** Output path for the trained model file. */
  output: string
  /** L1 regularization cost (0.0-1.0, default: 0.01). */
  lambda?: number
  /** Maximum number of training iterations (default: 100). */
  maxIter?: number
  /** Number of threads (undefined = auto-detect CPU cores). */
  maxThreads?: number
}

/** Returns the version of the lindera-nodejs package. */
export declare function version(): string
