//! Embedded cc-cedict dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedCcCedictLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-cc-cedict", EmbeddedCcCedictLoader);
