//! Embedded unidic dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedUniDicLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-unidic", EmbeddedUniDicLoader);
