#!/usr/bin/env bash
#
# Bumps the Lindera version across every file that hardcodes it and cannot
# derive it dynamically from the workspace root Cargo.toml (which stays the
# single source of truth for everything else: per-crate Cargo.toml files via
# `version = { workspace = true }`, lindera-python's pyproject.toml via
# `dynamic = ["version"]`, and the Makefile via `cargo metadata`).
#
# Usage:
#   scripts/bump-up-version.sh <new-version>
#
# Example:
#   scripts/bump-up-version.sh 1.2.3

set -euo pipefail

usage() {
  echo "Usage: $(basename "$0") <new-version>" >&2
  echo "Example: $(basename "$0") 1.2.3" >&2
  exit 1
}

if [[ $# -ne 1 ]]; then
  usage
fi

NEW_VERSION="$1"

if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: '$NEW_VERSION' is not a valid version (expected X.Y.Z)" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CURRENT_VERSION="$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -n1)"
if [[ -z "$CURRENT_VERSION" ]]; then
  echo "error: could not determine the current version from Cargo.toml" >&2
  exit 1
fi
if [[ "$CURRENT_VERSION" == "$NEW_VERSION" ]]; then
  echo "error: current version is already $NEW_VERSION" >&2
  exit 1
fi

echo "Bumping version: $CURRENT_VERSION -> $NEW_VERSION"

# Escaped for use inside a sed search pattern (the only special BRE
# character a X.Y.Z version string can contain is '.').
CURRENT_RE="${CURRENT_VERSION//./\\.}"

# --- Cargo.toml: workspace.package.version + every internal lindera-* pin ---
sed -i \
  -e "s/^version = \"$CURRENT_RE\"\$/version = \"$NEW_VERSION\"/" \
  -e "s/^\(lindera[a-z-]* = { version = \"\)$CURRENT_RE\(\"\)/\1$NEW_VERSION\2/" \
  Cargo.toml

# --- Cargo.lock: version field of every lindera-owned workspace member ---
# Path dependencies have no `source` line, so `version` always directly
# follows `name` for these entries.
sed -i "/^name = \"lindera/{n;s/^version = \"$CURRENT_RE\"\$/version = \"$NEW_VERSION\"/}" Cargo.lock

# --- lindera-ruby/lindera.gemspec ---
# No `^` anchor: the assignment is indented inside the `Gem::Specification.new`
# block, not at the start of the line.
sed -i "s/\(spec\.version = \"\)$CURRENT_RE\(\"\)/\1$NEW_VERSION\2/" lindera-ruby/lindera.gemspec

# --- lindera-nodejs/index.js: NAPI-generated binding-version guard ---
# Regenerated by `napi build`, but a version bump alone changes nothing else
# in this file, so a literal substitution reproduces the same output.
sed -i "s/$CURRENT_RE/$NEW_VERSION/g" lindera-nodejs/index.js

# --- docs: sample `version()` output in the WASM tokenizer API guide ---
sed -i "s/$CURRENT_RE/$NEW_VERSION/g" docs/src/lindera-wasm/tokenizer_api.md
sed -i "s/$CURRENT_RE/$NEW_VERSION/g" docs/ja/src/lindera-wasm/tokenizer_api.md

# --- package.json files: edit structurally via jq (same idiom as the
# --- Makefile's own wasm-package-json version sync) to avoid formatting risk.
for pkg_json in lindera-nodejs/package.json lindera-wasm/example/package.json; do
  tmp="$(mktemp)"
  jq --arg v "$NEW_VERSION" '.version = $v' "$pkg_json" > "$tmp"
  mv "$tmp" "$pkg_json"
done

# --- Sanity check: Cargo.lock must still agree with Cargo.toml ---
cargo metadata --locked --format-version=1 >/dev/null

# --- Safety net: warn about any other tracked file still mentioning the old
# --- version, so this script's file list can be extended before something is
# --- missed. `git grep` (fixed-string, tracked files only) keeps this scoped
# --- to real source: it never wanders into build artifacts, .gitignore'd
# --- vendored reference code, or generated docs output the way a plain
# --- recursive grep would. Changelogs legitimately keep old version numbers
# --- as history, and this script's own usage example isn't a real version
# --- reference either, so both are excluded.
leftovers="$(git grep -l --fixed-strings "$CURRENT_VERSION" -- . \
  ':(exclude)Cargo.lock' \
  ':(exclude)**/CHANGES.md' \
  ':(exclude)**/CHANGELOG.md' \
  ':(exclude)scripts/bump-up-version.sh' \
  2>/dev/null || true)"
if [[ -n "$leftovers" ]]; then
  echo
  echo "warning: the following files still mention $CURRENT_VERSION and were not updated by this script:" >&2
  echo "$leftovers" >&2
  echo "Review them and extend scripts/bump-up-version.sh if they should track the version." >&2
fi

echo
echo "Done. Review the diff, then run cargo fmt/clippy/test before committing."
