//! Embedded ipadic dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedIPADICLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-ipadic", EmbeddedIPADICLoader);
