//! Embedded jieba dictionary.
//!
//! Generated by [`lindera_dictionary::embedded_dictionary!`]. The public
//! `load()` function and `EmbeddedJiebaLoader` are produced by that macro.

lindera_dictionary::embedded_dictionary!("/lindera-jieba", EmbeddedJiebaLoader);
