name: Periodic Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  format:
    name: Format
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
        toolchain: [stable]
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run format
        run: cargo fmt --all -- --check

  test-lindera-crf:
    name: Test lindera-crf (${{ matrix.toolchain }})
    needs: [format]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-crf --all-features

  test-lindera-dictionary:
    name: Test lindera-dictionary (${{ matrix.platform.target }}, ${{ matrix.toolchain }})
    needs: [format, test-lindera-crf]
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: macos-15-intel
            target: x86_64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: windows-latest
            target: aarch64-pc-windows-msvc
            skip_test_run: true
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.platform.target }}
          components: rustfmt, clippy

      - name: Run test
        shell: bash
        run: |
          if [ "${{ matrix.platform.skip_test_run }}" == "true" ]; then
            cargo check -p lindera-dictionary --target "${{ matrix.platform.target }}" --all-features
          else
            cargo test -p lindera-dictionary --target "${{ matrix.platform.target }}" --all-features
          fi

  test-lindera-ipadic:
    name: Test lindera-ipadic (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-ipadic --all-features

  test-lindera-ipadic-neologd:
    name: Test lindera-ipadic-neologd (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-ipadic-neologd --all-features

  test-lindera-unidic:
    name: Test lindera-unidic (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-unidic --all-features

  test-lindera-ko-dic:
    name: Test lindera-ko-dic (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-ko-dic --all-features

  test-lindera-cc-cedict:
    name: Test lindera-cc-cedict (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-cc-cedict --all-features

  test-lindera-jieba:
    name: Test lindera-jieba (${{ matrix.toolchain }})
    needs: [test-lindera-dictionary]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-jieba --all-features

  test-lindera:
    name: Test lindera (${{ matrix.platform.target }}, ${{ matrix.toolchain }})
    needs:
      - test-lindera-dictionary
      - test-lindera-ipadic
      - test-lindera-ipadic-neologd
      - test-lindera-unidic
      - test-lindera-ko-dic
      - test-lindera-cc-cedict
      - test-lindera-jieba
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: macos-15-intel
            target: x86_64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: windows-latest
            target: aarch64-pc-windows-msvc
            skip_test_run: true
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.platform.target }}
          components: rustfmt, clippy

      - name: Run test
        shell: bash
        run: |
          if [ "${{ matrix.platform.skip_test_run }}" == "true" ]; then
            cargo check -p lindera --target "${{ matrix.platform.target }}" --all-features
          else
            cargo test -p lindera --target "${{ matrix.platform.target }}" --all-features
          fi

  test-lindera-cli:
    name: Test lindera-cli (${{ matrix.toolchain }})
    needs: [test-lindera]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Run test
        run: cargo test -p lindera-cli --all-features

  test-lindera-python:
    name: Test lindera-python
    needs: [test-lindera]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Run Python test
        shell: bash
        run: |
          make init
          make python-test

  test-lindera-nodejs:
    name: Test lindera-nodejs
    needs: [test-lindera]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Run Node.js build
        run: cargo build -p lindera-nodejs --all-features

  test-lindera-wasm:
    name: Test lindera-wasm
    needs: [test-lindera]
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run WASM test
        run: make wasm-test
